### ISSUE TITLE
Remove isSaving/isLoading and replace by isCreating/isRemoving...

### ISSUE THREAD

**Issue by amaurymartiny** [feathers-plus/feathers-redux#38]
# Proposal: 

- Remove isSaving, isLoading and isFinished
- Replace by isCreating, isGetting, isFinding, isPatching, isUpdating and isRemoving...

## Motivation

I often do the following, in my React component, to do something when a resource has been loaded.

```javascript
componentWillReceiveProps(nextProps) {
  if (this.props.feathersUsers.isLoading && !nextProps.feathersUsers.isLoading) {
    // Do something when feathers finishes loading users
  }
}
```

However I wish to differentiate the behavior after patching a user or removing a user

```javascript
componentWillReceiveProps(nextProps) {
  if (this.props.feathersUsers.isSaving && !nextProps.feathersUsers.isSaving) {
    // How do we know if we patched, updated or removed a user?
  }
}
```

## Benefits

- Would follow the feathers way of having find/get/create/patch/update/remove for each service
- Would allow more fine-tuning (see Motivation)
- Users can always get `isLoading` with a selector on `isFinding || isGetting`

**Comment by eddyystop** [comment]
I agree the repo needs work in this area. I won't be able to get around to it until sometime in Jan 2018 because of work on Feathers Buzzard.

Are you interested in making a PR?

**Comment by bsubedi26** [comment]
@amaurymartiny, I actually had this problem also have this implemented in a locally forked repo for testing and its working well :). I could definitely submit a PR. Its actually a few lines of code.

Depending on the action you dispatch for the respective service, the state is changed to (`${actionName}Pending). For example, a create action (createPending: true), find action (findPending: true) ... (etc.).

```javascript
const reducerForServiceMethod = (actionType, ifLoading, isFind) => ({
const slicedActionType = actionType.slice(SERVICE_NAME.length, actionType.length).toLowerCase() // returns find/create/update/patch
...
})
```
When the promise has started returns the following state as always with the following addition:
```javascript
return ({
        ...state,
        [opts[`${slicedActionType}Pending`]]: true,
       ...
})
```
When the promise has resolved:
```javascript
return ({
        ...state,
        [opts[`${slicedActionType}Pending`]]: false,
       ...
})
```
When promise is rejected:
```javascript
return ({
        ...state,
        [opts[`${slicedActionType}Pending`]]: false,
})
```
That is all the code, you can look at this file for reference (https://github.com/bsubedi26/React-Node-Authentication/blob/master/src/lib/feathers-redux.js).

**Comment by amaurymartiny** [comment]
Looks good! Yes go ahead and submit the PR

**Comment by eddyystop** [comment]
+1 I love not working in a vacumn.

**Comment by bsubedi26** [comment]
PR request (https://github.com/feathers-plus/feathers-redux/pull/39).

**Comment by eddyystop** [comment]
I asked on the PR is the failing integration tests could be fixed.

**Comment by amaurymartiny** [comment]
Would it make sense to remove isSaving/isLoading after #39?

**Comment by eddyystop** [comment]
Quite possibly.

I plan to get my mind back into this repo in Feb once I finish some other Feathers work.
