### ISSUE TITLE
SSR Support

### ISSUE THREAD

**Issue by Sicria** [feathers-plus/feathers-redux#44]
If you attempt to call a method inside of ``asyncConnect`` during a SSR it throws an error.

```
Error: "value" required in setHeader("Cookie", value)
at convert (/opt/node_modules/feathers-errors/lib/index.js:245:79)
at toError (/opt/node_modules/feathers-rest/lib/client/base.js:24:37)
at <anonymous>
```

Fairly basic setup.
The ``helpers.services`` is ``bindWithDispatch`` of the services.
```
@asyncConnect([{
  promise: ({ helpers: { services } }) => {
    const promises = [];

    // Other promises etc...

    promises.push(services.conversion.find());

    // Run all promises without exiting even if one fails
    return Promise.all(promises.map(p => p.catch(e => e)));
  },
}])
```

For some reason it only does this on the first load when you've cleared cache. After the first load, this works as intended, but for first time visitors this data will not load unless they refresh.

Is there any way to set the cookie value?

**Comment by eddyystop** [comment]
I am not using asyncConnect so I don't know what its interface requirement are. You'll have to dig into this yourself.

I'll be happy to consider any contribution.
