### ISSUE TITLE
Is this project abandoned?

### ISSUE THREAD

**Issue by murbanowicz** [feathers-plus/feathers-redux#51]
Hi,

Is it abandoned? 
It looks great in terms of idea etc. but is it working? Can it be used in production? Is it going to be maintained?

**Comment by eddyystop** [comment]
This project does exactly what it was intended to do and it does it well. Its used in multiple production apps.

People have posted issues where they want the repo to mutate into a client-side cache. That is not what it is and, having some client-first experience, I beleive it would be the wrong way to go.
